name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: FranciscoDastres
          template: classic
          base: "" 
          
          # Ajuste de tamaño para que se vea más grande
          config_display: regular
          # Esto ayuda a que el contenido no se amontone
          config_padding: 0, 8%

          # PLUGIN: Isocalendar (Vista 3D)
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

          # PLUGIN: Calendario de Commits (Año actual)
          # Lo configuramos para que ocupe buen espacio
          plugin_calendar: yes
          plugin_calendar_limit: 1

          # PLUGIN: Lenguajes más usados
          plugin_languages: yes
          plugin_languages_ignored: html, css, scss # Ignoramos estos para resaltar JS/TS/Node
          plugin_languages_details: bytes-size, percentage
          plugin_languages_sections: most-used
          plugin_languages_limit: 8 # Muestra tu top 8 de lenguajes
          plugin_languages_recent_days: 14 # Resalta lo que has usado últimamente
